### ISSUE TITLE
Chrome (v52) FL extension is no longer working for ESPN.

### ISSUE THREAD

**Issue by MGT656student** [sglantz/FantasyLink#5] opened 2016-08-06 17:17 UTC
The icons do not show up on the page.

**Comment by greenice88** [comment] 2016-08-12 13:35
I am having the same issue.  The icon is also grayed out in the toolbar.

**Comment by Martschink** [comment] 2016-08-12 17:38
I've submitted a pull request to fix this and make the extension work on player rater and watchlist pages.

**Comment by sglantz** [comment] 2016-08-14 00:08
Thanks for the heads up.  I didn't realize that ESPN changed their URL scheme last week which is the cause for the extension breaking.  The fix that @Martschink submitted does work, but I have asked them to revise part of it and resubmit.  If you need an immediate fix, you can download that version and load it as an unpacked extension.  Once the new pull request is submitted and merged, I will push out the update through the Chrome Web Store.

**Comment by sglantz** [comment] 2016-08-14 01:13
I just finished uploading the fix to the Chrome Web Store.  It should be pushed out be Google shortly.

**Closed by sglantz** 2016-08-14 01:13 UTC
